package net.mips.compiler;

public enum Tokens {
	ID_TOKEN, NUM_TOKEN, PROGRAM_TOKEN, CONST_TOKEN,
	VAR_TOKEN, BEGIN_TOKEN, END_TOKEN, IF_TOKEN,
	THEN_TOKEN, WHILE_TOKEN, DO_TOKEN, WRITE_TOKEN,
	READ_TOKEN, EG_TOKEN, DIFF_TOKEN, SUP_TOKEN,
	INF_TOKEN, SUPEG_TOKEN, INFEG_TOKEN, AFFEC_TOKEN,
	PLUS_TOKEN, MOINS_TOKEN, MUL_TOKEN, DIV_TOKEN,
	PARG_TOKEN, PARD_TOKEN, VIR_TOKEN, PVIR_TOKEN,
	PNT_TOKEN, EOF_TOKEN, ERR_TOKEN
}
